### ISSUE TITLE
Success file of session, then fail redis of session.

### ISSUE THREAD

**Issue by zero12a** [upscalesoftware/swoole-session#2] opened 2021-04-28 08:36 UTC
Dear friends.

Session management with files was successful in the swoole environment, 
but session information cannot be generated on the redis server when managing sessions with redis.

**<< test result >>**

nginx + php-fpm = redis session test success

nginx + php-fpm = file session test success

swoole + SessionMiddleware = file session test succes  (session.save_handler=file)

swoole + SessionMiddleware = redis session test fail (session.save_handler=redis)

**<< php.ini - fail config >>**

session.save_handler=redis

session.save_path="tcp://localhost:6379?auth=1234"
 

php : 7.4.15

swoole : 4.6.5

**Comment by sshymko** [comment] 2021-05-16 03:30
@zero12a 
Thanks for your report! My apologies for the delayed reply.

Tested both files session storage and Redis without any issue.
Went ahead and implemented functional tests powered by GitHub Actions.
The test suite completes successfully on latest versions of PHP, Swoole, and Redis.
Here's the successful run of Swoole 4.6.5 on PHP 7.4 against Redis 6:
https://github.com/upscalesoftware/swoole-session/runs/2593086655

Please try running the test suite on your local environment:
```bash
vendor/bin/phpunit -d session.save_handler=redis -d session.save_path=tcp://localhost:6379
```

If it fails, let's narrow down the issue to the specific combination of PHP/Swoole/Redis versions.

**Comment by sshymko** [comment] 2021-06-13 03:50
Closing as Cannot Reproduce.

**Closed as completed by sshymko** 2021-06-13 03:50 UTC
